version: "3.2"
services:
  nodejs:
    build:
      context: .
    networks:
      - frontend
      - backend
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: moe-nodejs-app
networks:
  frontend:
  backend: